# Generated by Django 4.2.4 on 2024-02-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetsale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetsale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
