# Generated by Django 4.2.4 on 2024-02-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internet',
            name='simcard_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Credit', 'Credit')], max_length=50),
        ),
    ]
